version: '3'
<<<<<<< HEAD
<<<<<<< HEAD
=======

>>>>>>> ce326e6bc3a5a1624c63b776bb6ba1fab3d1d33c
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../VUEJS/.env:/.env  # Mount .env file into the frontend container
    ports:
      - "5173:5173"  # Map port 5173 of the container to port 5173 on the host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
<<<<<<< HEAD
      - ./backend:/app
      - ../VUEJS/.env:/app/.env  # Mount the same directory for backend
=======

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../VUEJS/.env:/.env  # Mount .env file into the frontend container
    ports:
      - "5173:5173"  # Map port 5173 of the container to port 5173 on the host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
=======
>>>>>>> ce326e6bc3a5a1624c63b776bb6ba1fab3d1d33c
      - ../VUEJS/.env:/.env  # Mount .env file into the backend container
    ports:
      - "5171:5171"  # Map port 5171 of the container to port 5171 on the host
    depends_on:
      - frontend
<<<<<<< HEAD

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
>>>>>>> Newway
=======
>>>>>>> ce326e6bc3a5a1624c63b776bb6ba1fab3d1d33c
