global:
  scrape_interval: 15s # How frequently Prometheus should scrape targets

scrape_configs:
  - job_name: 'your_service_name'
    static_configs:
      - targets: ['backend:5171'] # Replace 'backend' with the name of your backend service defined in Docker Compose
