FROM php:7.4-apache

# ENV COMPOSER_ALLOW_SUPERUSER=1
# RUN apt update && apt install -y zip git
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# RUN composer --version
# RUN composer require guzzlehttp/guzzle:^7.0

# COPY src/ /var/www/html
EXPOSE 80